version: '3.9'
services:
  api:
    container_name: nestjs-prod
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - nestjs-boilerplate-network

  postgres:
    image: postgres:17
    container_name: postgres_db_prod
    ports:
      - "25432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nestjs-boilerplate-network

networks:
  nestjs-boilerplate-network:
    driver: bridge
