services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`next-app.dokploy.com`)
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.tls.certResolver=letsencrypt
      - traefik.http.services.api.loadbalancer.server.port=8000
  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - "25432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
