services:
  api:
    container_name: nestjs-prod
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
      - .env.${NODE_ENV} # .env.production or .env.development
    ports:
      - "8081:8000"
    networks:
      - nestjs-boilerplate-network

  postgres:
    image: postgres:17
    container_name: postgres_db_prod
    ports:
      - "25432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nestjs-boilerplate-network

networks:
  nestjs-boilerplate-network:
    driver: bridge
