services:
  nestjs-boilerplate-api:
    container_name: nestjs-boilerplate-api-local
    restart: always

    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
      - .env.production
    ports:
      - "8000:8000"
    networks:
      - nestjs-boilerplate-network

  postgres:
    image: postgres:17
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nestjs-boilerplate-network


networks:
  nestjs-boilerplate-network:
    driver: bridge